### ISSUE TITLE
Support @media not ios

### ISSUE THREAD

**Issue by kristerkari** [kristerkari/react-native-css-media-query-processor#3]
Currently you can write this to only target iOS:

```css
@media ios {
  .myClass {
    font-size: 1rem;
  }
}
```

but it would be good to support the `not` operator too to target other type than ios:

```css
@media not ios {
  .myClass {
    font-size: 1rem;
  }
}
```
